export {FaRegClock, FaDollarSign,FaSlackHash,FaUser,FaFacebookSquare, FaCoins, FaUserEdit, FaTimes,FaMapMarkerAlt} from 'react-icons/fa'
export { TbDiscount2 } from 'react-icons/tb'
export { BsFillPinMapFill,BsPencilSquare,BsFillStarFill,BsBookmark,BsBookmarkStarFill,BsCheckAll,BsThreeDots,BsFacebook, BsFillPauseFill, BsPlayFill, BsTrash, BsStarHalf} from 'react-icons/bs'
export { AiOutlineMinus,AiTwotoneFire,AiOutlineInstagram,AiOutlineLoading3Quarters,AiOutlinePlus,AiOutlineCamera,AiOutlineEye ,AiOutlineUser} from 'react-icons/ai'
export { ImHome } from 'react-icons/im'
export { HiLocationMarker, HiViewGrid, HiOutlineMail, HiOutlineInformationCircle} from 'react-icons/hi'
export { SiTiktok } from 'react-icons/si'
export { RiCopyrightLine, RiArrowUpCircleFill } from 'react-icons/ri'
export { BiPowerOff, BiSearch, BiCheckShield } from 'react-icons/bi'
export { GrMapLocation } from 'react-icons/gr'
export { TiLocationArrowOutline } from 'react-icons/ti'
export {GrLinkPrevious, GrSearchAdvanced,GrFormPrevious,GrFormNext} from 'react-icons/gr'
export { FcGoogle } from 'react-icons/fc'
export {MdOutlineZoomInMap,MdOutlineZoomOutMap,MdMyLocation,MdOutlineLocationSearching} from 'react-icons/md'
export {PiCaretDoubleRightBold,PiCaretDoubleLeftBold} from 'react-icons/pi'

